title: Jan 2024
description: Schedule
theme: just-the-docs
color_scheme: foo

url: https://1000oaks.github.io

callouts:
  warning:
    color: red
  note:
    color: purple
  important:
    color: blue
  new:
    color: green
  highlight:
    color: yellow